<?php

/**
 * @file
 * The theme system, which controls the output of views map.
 *
 * This just adds a wrapper div to the map.
 */
 
 function _views_map_preprocess_views_map(&$vars) {
 
 }
 
 /**
 * The current element of the map.
 *
 * @ingroup themeable
 */
function theme_views_map_main_section($vars) {

}

/**
 * Views map: pager.
 *
 * @ingroup themeable
 */
function theme_views_map_pager_widget_render($vars) {

}


/**
 * Theme pager fields
 */
function _views_map_preprocess_views_map_pager_fields(&$vars) {

}


/**
 * Views map: pager item.
 *
 * @ingroup themeable
 */
function _views_map_preprocess_views_map_pager_field_item(&$vars) {

}

/**
 * Views map: Controls.
 *
 * @inggroup themeable
 */
function theme_views_map_controls_widget_render($vars) {

}


/**
 * The map controls.
 *
 * @ingroup themeable
 */
function _views_map_preprocess_views_map_controls_text(&$vars) {

}






